"""initial schema

Revision ID: 36c1a5eee24d
Revises: 
Create Date: 2026-08-26 11:28:59.889138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36c1a5eee24d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required for pg_trgm-backed fuzzy voter name search (idx_voters_name_trgm
    # below). Autogenerate can't detect/create extensions — added by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constituency_name', sa.String(length=150), nullable=True),
    sa.Column('constituency_no', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('lok_sabha_constituency', sa.String(length=150), nullable=True),
    sa.Column('current_mla', sa.String(length=150), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('total_mandals', sa.Integer(), nullable=True),
    sa.Column('total_villages', sa.Integer(), nullable=True),
    sa.Column('total_population', sa.BigInteger(), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mp3_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_added', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('press_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_added', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('scheme_name', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('badge_text', sa.String(length=100), nullable=True),
    sa.Column('service_provider', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_schemes_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code')
    )
    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("role IN ('super_admin','admin')", name='ck_staff_users_role'),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_staff_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('video_source', sa.String(length=20), nullable=False),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('video_file_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('upload_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.CheckConstraint("video_source IN ('youtube','upload')", name='ck_videos_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_added', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("category IN ('leaders','events','spiritual','inaugurations','sports','others')", name='ck_gallery_photos_category'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandal_id', 'name')
    )
    op.create_table('booths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booth_number', sa.String(length=20), nullable=False),
    sa.Column('booth_name', sa.String(length=150), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('total_voters', sa.Integer(), nullable=False),
    sa.Column('booth_officer_name', sa.String(length=150), nullable=True),
    sa.Column('booth_officer_mobile', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandal_id', 'booth_number')
    )
    op.create_table('development_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('pending','in_progress','completed')", name='ck_devworks_status'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('chief_guest', sa.String(length=150), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('mandal_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('upcoming','completed','cancelled')", name='ck_events_status'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epic_no', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('relation_name', sa.String(length=150), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=255), nullable=True),
    sa.Column('house_no', sa.String(length=50), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('booth_id', sa.Integer(), nullable=True),
    sa.Column('voted_last_election', sa.Boolean(), nullable=True),
    sa.Column('is_new_voter', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("gender IN ('Male','Female','Other')", name='ck_voters_gender'),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], ),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epic_no')
    )
    op.create_index('idx_voters_name_trgm', 'voters', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('epic_no', sa.String(length=20), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=150), nullable=False),
    sa.Column('relation_name', sa.String(length=150), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('bank_account_number', sa.String(length=30), nullable=True),
    sa.Column('ifsc_code', sa.String(length=15), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('scheme_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','disbursed')", name='ck_beneficiaries_status'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('epic_no', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('mandal_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('new','read','responded')", name='ck_contact_messages_status'),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('janata_darbar_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_number', sa.String(length=20), nullable=False),
    sa.Column('visitor_name', sa.String(length=150), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('epic_no', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('issue_category', sa.String(length=100), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('mandal_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','in_progress','resolved','referred')", name='ck_janata_darbar_status'),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_number')
    )
    op.create_table('local_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader_name', sa.String(length=150), nullable=False),
    sa.Column('alias_name', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('party', sa.String(length=100), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('epic_no', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('related_person', sa.String(length=150), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('epic_no', sa.String(length=20), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('mandal_id', sa.Integer(), nullable=True),
    sa.Column('notes_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high')", name='ck_notes_priority'),
    sa.CheckConstraint("status IN ('open','in_progress','closed')", name='ck_notes_status'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respondent_name', sa.String(length=150), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('epic_no', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('satisfaction_rating', sa.SmallInteger(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('mandal_id', sa.Integer(), nullable=True),
    sa.Column('survey_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('feedback_details', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('satisfaction_rating BETWEEN 1 AND 5', name='ck_surveys_rating'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Reporting views (db/schema.sql section 16) ---------------------
    # These live outside the SQLAlchemy model layer (queried via raw SQL in
    # app/api/routes/{voters,beneficiaries,reports,dashboard}.py), so
    # autogenerate can't detect or create them — added by hand, verbatim
    # from db/schema.sql.
    op.execute("""
        CREATE VIEW v_mandal_voter_summary AS
        SELECT
            m.id                                                   AS mandal_id,
            m.name                                                 AS mandal_name,
            COUNT(*) FILTER (WHERE v.gender = 'Male')               AS male_voters,
            COUNT(*) FILTER (WHERE v.gender = 'Female')             AS female_voters,
            COUNT(v.id)                                             AS total_voters,
            ROUND(100.0 * COUNT(v.id) / NULLIF(SUM(COUNT(v.id)) OVER (), 0), 2) AS pct_of_total
        FROM mandals m
        LEFT JOIN voters v ON v.mandal_id = m.id
        GROUP BY m.id, m.name
    """)

    op.execute("""
        CREATE VIEW v_voter_gender_distribution AS
        SELECT gender, COUNT(*) AS total
        FROM voters
        GROUP BY gender
    """)

    op.execute("""
        CREATE VIEW v_development_status_summary AS
        SELECT status, COUNT(*) AS total
        FROM development_works
        GROUP BY status
    """)

    op.execute("""
        CREATE VIEW v_beneficiaries_by_geography AS
        SELECT
            mn.name  AS mandal_name,
            vl.name  AS village_name,
            s.scheme_name,
            b.status,
            COUNT(*) AS beneficiary_count,
            SUM(b.amount) AS total_amount
        FROM beneficiaries b
        JOIN mandals mn ON mn.id = b.mandal_id
        JOIN villages vl ON vl.id = b.village_id
        JOIN schemes s ON s.id = b.scheme_id
        GROUP BY mn.name, vl.name, s.scheme_name, b.status
    """)

    op.execute("""
        CREATE VIEW v_scheme_performance AS
        SELECT
            s.scheme_name,
            COUNT(b.id)                                              AS total_applications,
            COUNT(*) FILTER (WHERE b.status = 'approved')             AS approved,
            COUNT(*) FILTER (WHERE b.status = 'pending')               AS pending,
            COALESCE(SUM(b.amount) FILTER (WHERE b.status = 'disbursed'), 0) AS amount_disbursed,
            ROUND(
                100.0 * COUNT(*) FILTER (WHERE b.status = 'approved') / NULLIF(COUNT(b.id), 0), 2
            ) AS approval_rate_pct
        FROM schemes s
        LEFT JOIN beneficiaries b ON b.scheme_id = s.id
        GROUP BY s.scheme_name
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_scheme_performance")
    op.execute("DROP VIEW IF EXISTS v_beneficiaries_by_geography")
    op.execute("DROP VIEW IF EXISTS v_development_status_summary")
    op.execute("DROP VIEW IF EXISTS v_voter_gender_distribution")
    op.execute("DROP VIEW IF EXISTS v_mandal_voter_summary")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveys')
    op.drop_table('notes_followups')
    op.drop_table('local_leaders')
    op.drop_table('janata_darbar_visits')
    op.drop_table('contact_messages')
    op.drop_table('beneficiaries')
    op.drop_index('idx_voters_name_trgm', table_name='voters', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('voters')
    op.drop_table('events')
    op.drop_table('development_works')
    op.drop_table('booths')
    op.drop_table('villages')
    op.drop_table('gallery_photos')
    op.drop_table('activity_log')
    op.drop_table('videos')
    op.drop_table('staff_users')
    op.drop_table('schemes')
    op.drop_table('press_gallery')
    op.drop_table('mp3_songs')
    op.drop_table('mandals')
    op.drop_table('app_settings')
    op.drop_table('achievements')
    # ### end Alembic commands ###
